//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.WSFacturaChile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosEmision", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatosEmision : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        private bool GenerarPDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        private int ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDFBase64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RutEmisor {
            get {
                return this.RutEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RutEmisorField, value) != true)) {
                    this.RutEmisorField = value;
                    this.RaisePropertyChanged("RutEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RutReceptor {
            get {
                return this.RutReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.RutReceptorField, value) != true)) {
                    this.RutReceptorField = value;
                    this.RaisePropertyChanged("RutReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool GenerarPDF {
            get {
                return this.GenerarPDFField;
            }
            set {
                if ((this.GenerarPDFField.Equals(value) != true)) {
                    this.GenerarPDFField = value;
                    this.RaisePropertyChanged("GenerarPDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string PDFBase64 {
            get {
                return this.PDFBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PDFBase64Field, value) != true)) {
                    this.PDFBase64Field = value;
                    this.RaisePropertyChanged("PDFBase64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosEstado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatosEstado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        private bool GenerarPDFField;
        
        private int ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDFBase64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool GenerarPDF {
            get {
                return this.GenerarPDFField;
            }
            set {
                if ((this.GenerarPDFField.Equals(value) != true)) {
                    this.GenerarPDFField = value;
                    this.RaisePropertyChanged("GenerarPDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PDFBase64 {
            get {
                return this.PDFBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PDFBase64Field, value) != true)) {
                    this.PDFBase64Field = value;
                    this.RaisePropertyChanged("PDFBase64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosEstadoAdv", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatosEstadoAdv : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        private bool GenerarPDFField;
        
        private int ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSIIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDFBase64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RutReceptor {
            get {
                return this.RutReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.RutReceptorField, value) != true)) {
                    this.RutReceptorField = value;
                    this.RaisePropertyChanged("RutReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool GenerarPDF {
            get {
                return this.GenerarPDFField;
            }
            set {
                if ((this.GenerarPDFField.Equals(value) != true)) {
                    this.GenerarPDFField = value;
                    this.RaisePropertyChanged("GenerarPDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Trx {
            get {
                return this.TrxField;
            }
            set {
                if ((object.ReferenceEquals(this.TrxField, value) != true)) {
                    this.TrxField = value;
                    this.RaisePropertyChanged("Trx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CodigoSII {
            get {
                return this.CodigoSIIField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSIIField, value) != true)) {
                    this.CodigoSIIField = value;
                    this.RaisePropertyChanged("CodigoSII");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEmisionField, value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PDFBase64 {
            get {
                return this.PDFBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PDFBase64Field, value) != true)) {
                    this.PDFBase64Field = value;
                    this.RaisePropertyChanged("PDFBase64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFacturaChile.WSServiciosSoap")]
    public interface WSServiciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento oDatosEmision del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/emisionDocumento", ReplyAction="*")]
        Web.WSFacturaChile.emisionDocumentoResponse emisionDocumento(Web.WSFacturaChile.emisionDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/emisionDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.WSFacturaChile.emisionDocumentoResponse> emisionDocumentoAsync(Web.WSFacturaChile.emisionDocumentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento oDatosEstado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarEstado", ReplyAction="*")]
        Web.WSFacturaChile.consultarEstadoResponse consultarEstado(Web.WSFacturaChile.consultarEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.WSFacturaChile.consultarEstadoResponse> consultarEstadoAsync(Web.WSFacturaChile.consultarEstadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento oDatosEstadoAdv del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarEstadoAdv", ReplyAction="*")]
        Web.WSFacturaChile.consultarEstadoAdvResponse consultarEstadoAdv(Web.WSFacturaChile.consultarEstadoAdvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarEstadoAdv", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.WSFacturaChile.consultarEstadoAdvResponse> consultarEstadoAdvAsync(Web.WSFacturaChile.consultarEstadoAdvRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emisionDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emisionDocumento", Namespace="http://tempuri.org/", Order=0)]
        public Web.WSFacturaChile.emisionDocumentoRequestBody Body;
        
        public emisionDocumentoRequest() {
        }
        
        public emisionDocumentoRequest(Web.WSFacturaChile.emisionDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class emisionDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.WSFacturaChile.DatosEmision oDatosEmision;
        
        public emisionDocumentoRequestBody() {
        }
        
        public emisionDocumentoRequestBody(Web.WSFacturaChile.DatosEmision oDatosEmision) {
            this.oDatosEmision = oDatosEmision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emisionDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emisionDocumentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.WSFacturaChile.emisionDocumentoResponseBody Body;
        
        public emisionDocumentoResponse() {
        }
        
        public emisionDocumentoResponse(Web.WSFacturaChile.emisionDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class emisionDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.WSFacturaChile.DatosEmision emisionDocumentoResult;
        
        public emisionDocumentoResponseBody() {
        }
        
        public emisionDocumentoResponseBody(Web.WSFacturaChile.DatosEmision emisionDocumentoResult) {
            this.emisionDocumentoResult = emisionDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarEstado", Namespace="http://tempuri.org/", Order=0)]
        public Web.WSFacturaChile.consultarEstadoRequestBody Body;
        
        public consultarEstadoRequest() {
        }
        
        public consultarEstadoRequest(Web.WSFacturaChile.consultarEstadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarEstadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.WSFacturaChile.DatosEstado oDatosEstado;
        
        public consultarEstadoRequestBody() {
        }
        
        public consultarEstadoRequestBody(Web.WSFacturaChile.DatosEstado oDatosEstado) {
            this.oDatosEstado = oDatosEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarEstadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.WSFacturaChile.consultarEstadoResponseBody Body;
        
        public consultarEstadoResponse() {
        }
        
        public consultarEstadoResponse(Web.WSFacturaChile.consultarEstadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarEstadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.WSFacturaChile.DatosEstado consultarEstadoResult;
        
        public consultarEstadoResponseBody() {
        }
        
        public consultarEstadoResponseBody(Web.WSFacturaChile.DatosEstado consultarEstadoResult) {
            this.consultarEstadoResult = consultarEstadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoAdvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarEstadoAdv", Namespace="http://tempuri.org/", Order=0)]
        public Web.WSFacturaChile.consultarEstadoAdvRequestBody Body;
        
        public consultarEstadoAdvRequest() {
        }
        
        public consultarEstadoAdvRequest(Web.WSFacturaChile.consultarEstadoAdvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarEstadoAdvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.WSFacturaChile.DatosEstadoAdv oDatosEstadoAdv;
        
        public consultarEstadoAdvRequestBody() {
        }
        
        public consultarEstadoAdvRequestBody(Web.WSFacturaChile.DatosEstadoAdv oDatosEstadoAdv) {
            this.oDatosEstadoAdv = oDatosEstadoAdv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoAdvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarEstadoAdvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.WSFacturaChile.consultarEstadoAdvResponseBody Body;
        
        public consultarEstadoAdvResponse() {
        }
        
        public consultarEstadoAdvResponse(Web.WSFacturaChile.consultarEstadoAdvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarEstadoAdvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.WSFacturaChile.DatosEstadoAdv consultarEstadoAdvResult;
        
        public consultarEstadoAdvResponseBody() {
        }
        
        public consultarEstadoAdvResponseBody(Web.WSFacturaChile.DatosEstadoAdv consultarEstadoAdvResult) {
            this.consultarEstadoAdvResult = consultarEstadoAdvResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSServiciosSoapChannel : Web.WSFacturaChile.WSServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSServiciosSoapClient : System.ServiceModel.ClientBase<Web.WSFacturaChile.WSServiciosSoap>, Web.WSFacturaChile.WSServiciosSoap {
        
        public WSServiciosSoapClient() {
        }
        
        public WSServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.WSFacturaChile.emisionDocumentoResponse Web.WSFacturaChile.WSServiciosSoap.emisionDocumento(Web.WSFacturaChile.emisionDocumentoRequest request) {
            return base.Channel.emisionDocumento(request);
        }
        
        public Web.WSFacturaChile.DatosEmision emisionDocumento(Web.WSFacturaChile.DatosEmision oDatosEmision) {
            Web.WSFacturaChile.emisionDocumentoRequest inValue = new Web.WSFacturaChile.emisionDocumentoRequest();
            inValue.Body = new Web.WSFacturaChile.emisionDocumentoRequestBody();
            inValue.Body.oDatosEmision = oDatosEmision;
            Web.WSFacturaChile.emisionDocumentoResponse retVal = ((Web.WSFacturaChile.WSServiciosSoap)(this)).emisionDocumento(inValue);
            return retVal.Body.emisionDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.WSFacturaChile.emisionDocumentoResponse> Web.WSFacturaChile.WSServiciosSoap.emisionDocumentoAsync(Web.WSFacturaChile.emisionDocumentoRequest request) {
            return base.Channel.emisionDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.WSFacturaChile.emisionDocumentoResponse> emisionDocumentoAsync(Web.WSFacturaChile.DatosEmision oDatosEmision) {
            Web.WSFacturaChile.emisionDocumentoRequest inValue = new Web.WSFacturaChile.emisionDocumentoRequest();
            inValue.Body = new Web.WSFacturaChile.emisionDocumentoRequestBody();
            inValue.Body.oDatosEmision = oDatosEmision;
            return ((Web.WSFacturaChile.WSServiciosSoap)(this)).emisionDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.WSFacturaChile.consultarEstadoResponse Web.WSFacturaChile.WSServiciosSoap.consultarEstado(Web.WSFacturaChile.consultarEstadoRequest request) {
            return base.Channel.consultarEstado(request);
        }
        
        public Web.WSFacturaChile.DatosEstado consultarEstado(Web.WSFacturaChile.DatosEstado oDatosEstado) {
            Web.WSFacturaChile.consultarEstadoRequest inValue = new Web.WSFacturaChile.consultarEstadoRequest();
            inValue.Body = new Web.WSFacturaChile.consultarEstadoRequestBody();
            inValue.Body.oDatosEstado = oDatosEstado;
            Web.WSFacturaChile.consultarEstadoResponse retVal = ((Web.WSFacturaChile.WSServiciosSoap)(this)).consultarEstado(inValue);
            return retVal.Body.consultarEstadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.WSFacturaChile.consultarEstadoResponse> Web.WSFacturaChile.WSServiciosSoap.consultarEstadoAsync(Web.WSFacturaChile.consultarEstadoRequest request) {
            return base.Channel.consultarEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.WSFacturaChile.consultarEstadoResponse> consultarEstadoAsync(Web.WSFacturaChile.DatosEstado oDatosEstado) {
            Web.WSFacturaChile.consultarEstadoRequest inValue = new Web.WSFacturaChile.consultarEstadoRequest();
            inValue.Body = new Web.WSFacturaChile.consultarEstadoRequestBody();
            inValue.Body.oDatosEstado = oDatosEstado;
            return ((Web.WSFacturaChile.WSServiciosSoap)(this)).consultarEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.WSFacturaChile.consultarEstadoAdvResponse Web.WSFacturaChile.WSServiciosSoap.consultarEstadoAdv(Web.WSFacturaChile.consultarEstadoAdvRequest request) {
            return base.Channel.consultarEstadoAdv(request);
        }
        
        public Web.WSFacturaChile.DatosEstadoAdv consultarEstadoAdv(Web.WSFacturaChile.DatosEstadoAdv oDatosEstadoAdv) {
            Web.WSFacturaChile.consultarEstadoAdvRequest inValue = new Web.WSFacturaChile.consultarEstadoAdvRequest();
            inValue.Body = new Web.WSFacturaChile.consultarEstadoAdvRequestBody();
            inValue.Body.oDatosEstadoAdv = oDatosEstadoAdv;
            Web.WSFacturaChile.consultarEstadoAdvResponse retVal = ((Web.WSFacturaChile.WSServiciosSoap)(this)).consultarEstadoAdv(inValue);
            return retVal.Body.consultarEstadoAdvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.WSFacturaChile.consultarEstadoAdvResponse> Web.WSFacturaChile.WSServiciosSoap.consultarEstadoAdvAsync(Web.WSFacturaChile.consultarEstadoAdvRequest request) {
            return base.Channel.consultarEstadoAdvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.WSFacturaChile.consultarEstadoAdvResponse> consultarEstadoAdvAsync(Web.WSFacturaChile.DatosEstadoAdv oDatosEstadoAdv) {
            Web.WSFacturaChile.consultarEstadoAdvRequest inValue = new Web.WSFacturaChile.consultarEstadoAdvRequest();
            inValue.Body = new Web.WSFacturaChile.consultarEstadoAdvRequestBody();
            inValue.Body.oDatosEstadoAdv = oDatosEstadoAdv;
            return ((Web.WSFacturaChile.WSServiciosSoap)(this)).consultarEstadoAdvAsync(inValue);
        }
    }
}
