//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.wsAmazonSige {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://www.norteamericano.cl/")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AP_PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AP_MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AP_Paterno {
            get {
                return this.AP_PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AP_PaternoField, value) != true)) {
                    this.AP_PaternoField = value;
                    this.RaisePropertyChanged("AP_Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AP_Materno {
            get {
                return this.AP_MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AP_MaternoField, value) != true)) {
                    this.AP_MaternoField = value;
                    this.RaisePropertyChanged("AP_Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Fecha_nacimiento {
            get {
                return this.Fecha_nacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_nacimientoField, value) != true)) {
                    this.Fecha_nacimientoField = value;
                    this.RaisePropertyChanged("Fecha_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelField, value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NVenta", Namespace="http://www.norteamericano.cl/")]
    [System.SerializableAttribute()]
    public partial class NVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime FechaBoletaField;
        
        private int NumeroMatriculaField;
        
        private Web.wsAmazonSige.CodigoSede SedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCursoField;
        
        private System.DateTime FechaInicioCursoField;
        
        private System.DateTime FechaTerminoCursoField;
        
        private int CantidadCursosField;
        
        private Web.wsAmazonSige.CodigoVenta TipoVentaField;
        
        private int ValorCursoField;
        
        private int TotalVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlosaVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlosaDescuentoField;
        
        private int MontoDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlosaRecargoField;
        
        private int MontoRecargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoBoletaField;
        
        private int ContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaBoleta {
            get {
                return this.FechaBoletaField;
            }
            set {
                if ((this.FechaBoletaField.Equals(value) != true)) {
                    this.FechaBoletaField = value;
                    this.RaisePropertyChanged("FechaBoleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroMatricula {
            get {
                return this.NumeroMatriculaField;
            }
            set {
                if ((this.NumeroMatriculaField.Equals(value) != true)) {
                    this.NumeroMatriculaField = value;
                    this.RaisePropertyChanged("NumeroMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Web.wsAmazonSige.CodigoSede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((this.SedeField.Equals(value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IdCurso {
            get {
                return this.IdCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCursoField, value) != true)) {
                    this.IdCursoField = value;
                    this.RaisePropertyChanged("IdCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaInicioCurso {
            get {
                return this.FechaInicioCursoField;
            }
            set {
                if ((this.FechaInicioCursoField.Equals(value) != true)) {
                    this.FechaInicioCursoField = value;
                    this.RaisePropertyChanged("FechaInicioCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaTerminoCurso {
            get {
                return this.FechaTerminoCursoField;
            }
            set {
                if ((this.FechaTerminoCursoField.Equals(value) != true)) {
                    this.FechaTerminoCursoField = value;
                    this.RaisePropertyChanged("FechaTerminoCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CantidadCursos {
            get {
                return this.CantidadCursosField;
            }
            set {
                if ((this.CantidadCursosField.Equals(value) != true)) {
                    this.CantidadCursosField = value;
                    this.RaisePropertyChanged("CantidadCursos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public Web.wsAmazonSige.CodigoVenta TipoVenta {
            get {
                return this.TipoVentaField;
            }
            set {
                if ((this.TipoVentaField.Equals(value) != true)) {
                    this.TipoVentaField = value;
                    this.RaisePropertyChanged("TipoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int ValorCurso {
            get {
                return this.ValorCursoField;
            }
            set {
                if ((this.ValorCursoField.Equals(value) != true)) {
                    this.ValorCursoField = value;
                    this.RaisePropertyChanged("ValorCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int TotalVenta {
            get {
                return this.TotalVentaField;
            }
            set {
                if ((this.TotalVentaField.Equals(value) != true)) {
                    this.TotalVentaField = value;
                    this.RaisePropertyChanged("TotalVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string GlosaVenta {
            get {
                return this.GlosaVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.GlosaVentaField, value) != true)) {
                    this.GlosaVentaField = value;
                    this.RaisePropertyChanged("GlosaVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string GlosaDescuento {
            get {
                return this.GlosaDescuentoField;
            }
            set {
                if ((object.ReferenceEquals(this.GlosaDescuentoField, value) != true)) {
                    this.GlosaDescuentoField = value;
                    this.RaisePropertyChanged("GlosaDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int MontoDescuento {
            get {
                return this.MontoDescuentoField;
            }
            set {
                if ((this.MontoDescuentoField.Equals(value) != true)) {
                    this.MontoDescuentoField = value;
                    this.RaisePropertyChanged("MontoDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string GlosaRecargo {
            get {
                return this.GlosaRecargoField;
            }
            set {
                if ((object.ReferenceEquals(this.GlosaRecargoField, value) != true)) {
                    this.GlosaRecargoField = value;
                    this.RaisePropertyChanged("GlosaRecargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int MontoRecargo {
            get {
                return this.MontoRecargoField;
            }
            set {
                if ((this.MontoRecargoField.Equals(value) != true)) {
                    this.MontoRecargoField = value;
                    this.RaisePropertyChanged("MontoRecargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string TipoBoleta {
            get {
                return this.TipoBoletaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoBoletaField, value) != true)) {
                    this.TipoBoletaField = value;
                    this.RaisePropertyChanged("TipoBoleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Contrato {
            get {
                return this.ContratoField;
            }
            set {
                if ((this.ContratoField.Equals(value) != true)) {
                    this.ContratoField = value;
                    this.RaisePropertyChanged("Contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Vendedor {
            get {
                return this.VendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendedorField, value) != true)) {
                    this.VendedorField = value;
                    this.RaisePropertyChanged("Vendedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodigoSede", Namespace="http://www.norteamericano.cl/")]
    public enum CodigoSede : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moneda = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Providencia = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LaFlorida = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empresas = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empresa = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodigoVenta", Namespace="http://www.norteamericano.cl/")]
    public enum CodigoVenta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Matricula = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SinMatricula = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CursosIndividuales = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmpresasSinMatricula = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmpresasConMatricula = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NUsuario", Namespace="http://www.norteamericano.cl/")]
    [System.SerializableAttribute()]
    public partial class NUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceEmisionRespuesta", Namespace="http://www.norteamericano.cl/")]
    [System.SerializableAttribute()]
    public partial class ServiceEmisionRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroBoletaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroBoleta {
            get {
                return this.NumeroBoletaField;
            }
            set {
                if ((this.NumeroBoletaField.Equals(value) != true)) {
                    this.NumeroBoletaField = value;
                    this.RaisePropertyChanged("NumeroBoleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Npago", Namespace="http://www.norteamericano.cl/")]
    [System.SerializableAttribute()]
    public partial class Npago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroBoletaField;
        
        private Web.wsAmazonSige.DocumentoPago FormaPagoField;
        
        private int MontoField;
        
        private int NumeroCuotaField;
        
        private System.DateTime FechaVencimientoField;
        
        private int RecargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlosaPagoField;
        
        private int OrdernCompraWebpayField;
        
        private int CodigoAutorizacionWebpayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDeudorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroChequeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroBoleta {
            get {
                return this.NumeroBoletaField;
            }
            set {
                if ((this.NumeroBoletaField.Equals(value) != true)) {
                    this.NumeroBoletaField = value;
                    this.RaisePropertyChanged("NumeroBoleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Web.wsAmazonSige.DocumentoPago FormaPago {
            get {
                return this.FormaPagoField;
            }
            set {
                if ((this.FormaPagoField.Equals(value) != true)) {
                    this.FormaPagoField = value;
                    this.RaisePropertyChanged("FormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumeroCuota {
            get {
                return this.NumeroCuotaField;
            }
            set {
                if ((this.NumeroCuotaField.Equals(value) != true)) {
                    this.NumeroCuotaField = value;
                    this.RaisePropertyChanged("NumeroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Recargo {
            get {
                return this.RecargoField;
            }
            set {
                if ((this.RecargoField.Equals(value) != true)) {
                    this.RecargoField = value;
                    this.RaisePropertyChanged("Recargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GlosaPago {
            get {
                return this.GlosaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.GlosaPagoField, value) != true)) {
                    this.GlosaPagoField = value;
                    this.RaisePropertyChanged("GlosaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int OrdernCompraWebpay {
            get {
                return this.OrdernCompraWebpayField;
            }
            set {
                if ((this.OrdernCompraWebpayField.Equals(value) != true)) {
                    this.OrdernCompraWebpayField = value;
                    this.RaisePropertyChanged("OrdernCompraWebpay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CodigoAutorizacionWebpay {
            get {
                return this.CodigoAutorizacionWebpayField;
            }
            set {
                if ((this.CodigoAutorizacionWebpayField.Equals(value) != true)) {
                    this.CodigoAutorizacionWebpayField = value;
                    this.RaisePropertyChanged("CodigoAutorizacionWebpay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string IdDeudor {
            get {
                return this.IdDeudorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDeudorField, value) != true)) {
                    this.IdDeudorField = value;
                    this.RaisePropertyChanged("IdDeudor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string IdCajero {
            get {
                return this.IdCajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajeroField, value) != true)) {
                    this.IdCajeroField = value;
                    this.RaisePropertyChanged("IdCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string NumeroCheque {
            get {
                return this.NumeroChequeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroChequeField, value) != true)) {
                    this.NumeroChequeField = value;
                    this.RaisePropertyChanged("NumeroCheque");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoPago", Namespace="http://www.norteamericano.cl/")]
    public enum DocumentoPago : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Efec_internacional = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Efec_estado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cheque = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TarjetaCredito = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TarjetaDebito = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pagare = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorFacturar = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NCliente", Namespace="http://www.norteamericano.cl/")]
    [System.SerializableAttribute()]
    public partial class NCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Web.wsAmazonSige.Documento TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        private int FonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Web.wsAmazonSige.Documento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Comuna {
            get {
                return this.ComunaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaField, value) != true)) {
                    this.ComunaField = value;
                    this.RaisePropertyChanged("Comuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Fono {
            get {
                return this.FonoField;
            }
            set {
                if ((this.FonoField.Equals(value) != true)) {
                    this.FonoField = value;
                    this.RaisePropertyChanged("Fono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://www.norteamericano.cl/")]
    public enum Documento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rut = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pasaporte = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.norteamericano.cl/", ConfigurationName="wsAmazonSige.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RutPasaporte del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/NivelIdiomaCliente", ReplyAction="*")]
        Web.wsAmazonSige.NivelIdiomaClienteResponse NivelIdiomaCliente(Web.wsAmazonSige.NivelIdiomaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/NivelIdiomaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.NivelIdiomaClienteResponse> NivelIdiomaClienteAsync(Web.wsAmazonSige.NivelIdiomaClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento venta del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaVenta", ReplyAction="*")]
        Web.wsAmazonSige.GrabaVentaResponse GrabaVenta(Web.wsAmazonSige.GrabaVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaVentaResponse> GrabaVentaAsync(Web.wsAmazonSige.GrabaVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento venta del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaVentaIchn", ReplyAction="*")]
        Web.wsAmazonSige.GrabaVentaIchnResponse GrabaVentaIchn(Web.wsAmazonSige.GrabaVentaIchnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaVentaIchn", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaVentaIchnResponse> GrabaVentaIchnAsync(Web.wsAmazonSige.GrabaVentaIchnRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pago del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaPago", ReplyAction="*")]
        Web.wsAmazonSige.GrabaPagoResponse GrabaPago(Web.wsAmazonSige.GrabaPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaPago", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaPagoResponse> GrabaPagoAsync(Web.wsAmazonSige.GrabaPagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pago del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaPagoCheque", ReplyAction="*")]
        Web.wsAmazonSige.GrabaPagoChequeResponse GrabaPagoCheque(Web.wsAmazonSige.GrabaPagoChequeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaPagoCheque", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaPagoChequeResponse> GrabaPagoChequeAsync(Web.wsAmazonSige.GrabaPagoChequeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaCliente", ReplyAction="*")]
        Web.wsAmazonSige.GrabaClienteResponse GrabaCliente(Web.wsAmazonSige.GrabaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/GrabaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaClienteResponse> GrabaClienteAsync(Web.wsAmazonSige.GrabaClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/ActualizaCorrelativoBoleta", ReplyAction="*")]
        Web.wsAmazonSige.ActualizaCorrelativoBoletaResponse ActualizaCorrelativoBoleta(Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/ActualizaCorrelativoBoleta", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.ActualizaCorrelativoBoletaResponse> ActualizaCorrelativoBoletaAsync(Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/EliminarVentaSinBoleta", ReplyAction="*")]
        Web.wsAmazonSige.EliminarVentaSinBoletaResponse EliminarVentaSinBoleta(Web.wsAmazonSige.EliminarVentaSinBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/EliminarVentaSinBoleta", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.EliminarVentaSinBoletaResponse> EliminarVentaSinBoletaAsync(Web.wsAmazonSige.EliminarVentaSinBoletaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://www.norteamericano.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/InicioSesion", ReplyAction="*")]
        Web.wsAmazonSige.InicioSesionResponse InicioSesion(Web.wsAmazonSige.InicioSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.norteamericano.cl/InicioSesion", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.wsAmazonSige.InicioSesionResponse> InicioSesionAsync(Web.wsAmazonSige.InicioSesionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NivelIdiomaClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NivelIdiomaCliente", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.NivelIdiomaClienteRequestBody Body;
        
        public NivelIdiomaClienteRequest() {
        }
        
        public NivelIdiomaClienteRequest(Web.wsAmazonSige.NivelIdiomaClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class NivelIdiomaClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RutPasaporte;
        
        public NivelIdiomaClienteRequestBody() {
        }
        
        public NivelIdiomaClienteRequestBody(string RutPasaporte) {
            this.RutPasaporte = RutPasaporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NivelIdiomaClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NivelIdiomaClienteResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.NivelIdiomaClienteResponseBody Body;
        
        public NivelIdiomaClienteResponse() {
        }
        
        public NivelIdiomaClienteResponse(Web.wsAmazonSige.NivelIdiomaClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class NivelIdiomaClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.Resultado NivelIdiomaClienteResult;
        
        public NivelIdiomaClienteResponseBody() {
        }
        
        public NivelIdiomaClienteResponseBody(Web.wsAmazonSige.Resultado NivelIdiomaClienteResult) {
            this.NivelIdiomaClienteResult = NivelIdiomaClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaVenta", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaVentaRequestBody Body;
        
        public GrabaVentaRequest() {
        }
        
        public GrabaVentaRequest(Web.wsAmazonSige.GrabaVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.NVenta venta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        public GrabaVentaRequestBody() {
        }
        
        public GrabaVentaRequestBody(Web.wsAmazonSige.NVenta venta, Web.wsAmazonSige.NUsuario usuario) {
            this.venta = venta;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaVentaResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaVentaResponseBody Body;
        
        public GrabaVentaResponse() {
        }
        
        public GrabaVentaResponse(Web.wsAmazonSige.GrabaVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.ServiceEmisionRespuesta GrabaVentaResult;
        
        public GrabaVentaResponseBody() {
        }
        
        public GrabaVentaResponseBody(Web.wsAmazonSige.ServiceEmisionRespuesta GrabaVentaResult) {
            this.GrabaVentaResult = GrabaVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaVentaIchnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaVentaIchn", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaVentaIchnRequestBody Body;
        
        public GrabaVentaIchnRequest() {
        }
        
        public GrabaVentaIchnRequest(Web.wsAmazonSige.GrabaVentaIchnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaVentaIchnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.NVenta venta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numeroBoleta;
        
        public GrabaVentaIchnRequestBody() {
        }
        
        public GrabaVentaIchnRequestBody(Web.wsAmazonSige.NVenta venta, Web.wsAmazonSige.NUsuario usuario, int numeroBoleta) {
            this.venta = venta;
            this.usuario = usuario;
            this.numeroBoleta = numeroBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaVentaIchnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaVentaIchnResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaVentaIchnResponseBody Body;
        
        public GrabaVentaIchnResponse() {
        }
        
        public GrabaVentaIchnResponse(Web.wsAmazonSige.GrabaVentaIchnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaVentaIchnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.ServiceEmisionRespuesta GrabaVentaIchnResult;
        
        public GrabaVentaIchnResponseBody() {
        }
        
        public GrabaVentaIchnResponseBody(Web.wsAmazonSige.ServiceEmisionRespuesta GrabaVentaIchnResult) {
            this.GrabaVentaIchnResult = GrabaVentaIchnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaPago", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaPagoRequestBody Body;
        
        public GrabaPagoRequest() {
        }
        
        public GrabaPagoRequest(Web.wsAmazonSige.GrabaPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.Npago pago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        public GrabaPagoRequestBody() {
        }
        
        public GrabaPagoRequestBody(Web.wsAmazonSige.Npago pago, Web.wsAmazonSige.NUsuario usuario) {
            this.pago = pago;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaPagoResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaPagoResponseBody Body;
        
        public GrabaPagoResponse() {
        }
        
        public GrabaPagoResponse(Web.wsAmazonSige.GrabaPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GrabaPagoResult;
        
        public GrabaPagoResponseBody() {
        }
        
        public GrabaPagoResponseBody(string GrabaPagoResult) {
            this.GrabaPagoResult = GrabaPagoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaPagoChequeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaPagoCheque", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaPagoChequeRequestBody Body;
        
        public GrabaPagoChequeRequest() {
        }
        
        public GrabaPagoChequeRequest(Web.wsAmazonSige.GrabaPagoChequeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaPagoChequeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.Npago pago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipoVenta;
        
        public GrabaPagoChequeRequestBody() {
        }
        
        public GrabaPagoChequeRequestBody(Web.wsAmazonSige.Npago pago, Web.wsAmazonSige.NUsuario usuario, string tipoVenta) {
            this.pago = pago;
            this.usuario = usuario;
            this.tipoVenta = tipoVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaPagoChequeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaPagoChequeResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaPagoChequeResponseBody Body;
        
        public GrabaPagoChequeResponse() {
        }
        
        public GrabaPagoChequeResponse(Web.wsAmazonSige.GrabaPagoChequeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaPagoChequeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GrabaPagoChequeResult;
        
        public GrabaPagoChequeResponseBody() {
        }
        
        public GrabaPagoChequeResponseBody(string GrabaPagoChequeResult) {
            this.GrabaPagoChequeResult = GrabaPagoChequeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaCliente", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaClienteRequestBody Body;
        
        public GrabaClienteRequest() {
        }
        
        public GrabaClienteRequest(Web.wsAmazonSige.GrabaClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.NCliente cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        public GrabaClienteRequestBody() {
        }
        
        public GrabaClienteRequestBody(Web.wsAmazonSige.NCliente cliente, Web.wsAmazonSige.NUsuario usuario) {
            this.cliente = cliente;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabaClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabaClienteResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.GrabaClienteResponseBody Body;
        
        public GrabaClienteResponse() {
        }
        
        public GrabaClienteResponse(Web.wsAmazonSige.GrabaClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class GrabaClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GrabaClienteResult;
        
        public GrabaClienteResponseBody() {
        }
        
        public GrabaClienteResponseBody(string GrabaClienteResult) {
            this.GrabaClienteResult = GrabaClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaCorrelativoBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizaCorrelativoBoleta", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.ActualizaCorrelativoBoletaRequestBody Body;
        
        public ActualizaCorrelativoBoletaRequest() {
        }
        
        public ActualizaCorrelativoBoletaRequest(Web.wsAmazonSige.ActualizaCorrelativoBoletaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class ActualizaCorrelativoBoletaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        public ActualizaCorrelativoBoletaRequestBody() {
        }
        
        public ActualizaCorrelativoBoletaRequestBody(Web.wsAmazonSige.NUsuario usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaCorrelativoBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizaCorrelativoBoletaResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.ActualizaCorrelativoBoletaResponseBody Body;
        
        public ActualizaCorrelativoBoletaResponse() {
        }
        
        public ActualizaCorrelativoBoletaResponse(Web.wsAmazonSige.ActualizaCorrelativoBoletaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizaCorrelativoBoletaResponseBody {
        
        public ActualizaCorrelativoBoletaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarVentaSinBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarVentaSinBoleta", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.EliminarVentaSinBoletaRequestBody Body;
        
        public EliminarVentaSinBoletaRequest() {
        }
        
        public EliminarVentaSinBoletaRequest(Web.wsAmazonSige.EliminarVentaSinBoletaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class EliminarVentaSinBoletaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int correlativo;
        
        public EliminarVentaSinBoletaRequestBody() {
        }
        
        public EliminarVentaSinBoletaRequestBody(Web.wsAmazonSige.NUsuario usuario, int correlativo) {
            this.usuario = usuario;
            this.correlativo = correlativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarVentaSinBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarVentaSinBoletaResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.EliminarVentaSinBoletaResponseBody Body;
        
        public EliminarVentaSinBoletaResponse() {
        }
        
        public EliminarVentaSinBoletaResponse(Web.wsAmazonSige.EliminarVentaSinBoletaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarVentaSinBoletaResponseBody {
        
        public EliminarVentaSinBoletaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicioSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InicioSesion", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.InicioSesionRequestBody Body;
        
        public InicioSesionRequest() {
        }
        
        public InicioSesionRequest(Web.wsAmazonSige.InicioSesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class InicioSesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.wsAmazonSige.NUsuario usuario;
        
        public InicioSesionRequestBody() {
        }
        
        public InicioSesionRequestBody(Web.wsAmazonSige.NUsuario usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicioSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InicioSesionResponse", Namespace="http://www.norteamericano.cl/", Order=0)]
        public Web.wsAmazonSige.InicioSesionResponseBody Body;
        
        public InicioSesionResponse() {
        }
        
        public InicioSesionResponse(Web.wsAmazonSige.InicioSesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.norteamericano.cl/")]
    public partial class InicioSesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InicioSesionResult;
        
        public InicioSesionResponseBody() {
        }
        
        public InicioSesionResponseBody(bool InicioSesionResult) {
            this.InicioSesionResult = InicioSesionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Web.wsAmazonSige.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Web.wsAmazonSige.ServiceSoap>, Web.wsAmazonSige.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.NivelIdiomaClienteResponse Web.wsAmazonSige.ServiceSoap.NivelIdiomaCliente(Web.wsAmazonSige.NivelIdiomaClienteRequest request) {
            return base.Channel.NivelIdiomaCliente(request);
        }
        
        public Web.wsAmazonSige.Resultado NivelIdiomaCliente(string RutPasaporte) {
            Web.wsAmazonSige.NivelIdiomaClienteRequest inValue = new Web.wsAmazonSige.NivelIdiomaClienteRequest();
            inValue.Body = new Web.wsAmazonSige.NivelIdiomaClienteRequestBody();
            inValue.Body.RutPasaporte = RutPasaporte;
            Web.wsAmazonSige.NivelIdiomaClienteResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).NivelIdiomaCliente(inValue);
            return retVal.Body.NivelIdiomaClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.NivelIdiomaClienteResponse> Web.wsAmazonSige.ServiceSoap.NivelIdiomaClienteAsync(Web.wsAmazonSige.NivelIdiomaClienteRequest request) {
            return base.Channel.NivelIdiomaClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.NivelIdiomaClienteResponse> NivelIdiomaClienteAsync(string RutPasaporte) {
            Web.wsAmazonSige.NivelIdiomaClienteRequest inValue = new Web.wsAmazonSige.NivelIdiomaClienteRequest();
            inValue.Body = new Web.wsAmazonSige.NivelIdiomaClienteRequestBody();
            inValue.Body.RutPasaporte = RutPasaporte;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).NivelIdiomaClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.GrabaVentaResponse Web.wsAmazonSige.ServiceSoap.GrabaVenta(Web.wsAmazonSige.GrabaVentaRequest request) {
            return base.Channel.GrabaVenta(request);
        }
        
        public Web.wsAmazonSige.ServiceEmisionRespuesta GrabaVenta(Web.wsAmazonSige.NVenta venta, Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.GrabaVentaRequest inValue = new Web.wsAmazonSige.GrabaVentaRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaVentaRequestBody();
            inValue.Body.venta = venta;
            inValue.Body.usuario = usuario;
            Web.wsAmazonSige.GrabaVentaResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaVenta(inValue);
            return retVal.Body.GrabaVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaVentaResponse> Web.wsAmazonSige.ServiceSoap.GrabaVentaAsync(Web.wsAmazonSige.GrabaVentaRequest request) {
            return base.Channel.GrabaVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaVentaResponse> GrabaVentaAsync(Web.wsAmazonSige.NVenta venta, Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.GrabaVentaRequest inValue = new Web.wsAmazonSige.GrabaVentaRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaVentaRequestBody();
            inValue.Body.venta = venta;
            inValue.Body.usuario = usuario;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.GrabaVentaIchnResponse Web.wsAmazonSige.ServiceSoap.GrabaVentaIchn(Web.wsAmazonSige.GrabaVentaIchnRequest request) {
            return base.Channel.GrabaVentaIchn(request);
        }
        
        public Web.wsAmazonSige.ServiceEmisionRespuesta GrabaVentaIchn(Web.wsAmazonSige.NVenta venta, Web.wsAmazonSige.NUsuario usuario, int numeroBoleta) {
            Web.wsAmazonSige.GrabaVentaIchnRequest inValue = new Web.wsAmazonSige.GrabaVentaIchnRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaVentaIchnRequestBody();
            inValue.Body.venta = venta;
            inValue.Body.usuario = usuario;
            inValue.Body.numeroBoleta = numeroBoleta;
            Web.wsAmazonSige.GrabaVentaIchnResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaVentaIchn(inValue);
            return retVal.Body.GrabaVentaIchnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaVentaIchnResponse> Web.wsAmazonSige.ServiceSoap.GrabaVentaIchnAsync(Web.wsAmazonSige.GrabaVentaIchnRequest request) {
            return base.Channel.GrabaVentaIchnAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaVentaIchnResponse> GrabaVentaIchnAsync(Web.wsAmazonSige.NVenta venta, Web.wsAmazonSige.NUsuario usuario, int numeroBoleta) {
            Web.wsAmazonSige.GrabaVentaIchnRequest inValue = new Web.wsAmazonSige.GrabaVentaIchnRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaVentaIchnRequestBody();
            inValue.Body.venta = venta;
            inValue.Body.usuario = usuario;
            inValue.Body.numeroBoleta = numeroBoleta;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaVentaIchnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.GrabaPagoResponse Web.wsAmazonSige.ServiceSoap.GrabaPago(Web.wsAmazonSige.GrabaPagoRequest request) {
            return base.Channel.GrabaPago(request);
        }
        
        public string GrabaPago(Web.wsAmazonSige.Npago pago, Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.GrabaPagoRequest inValue = new Web.wsAmazonSige.GrabaPagoRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaPagoRequestBody();
            inValue.Body.pago = pago;
            inValue.Body.usuario = usuario;
            Web.wsAmazonSige.GrabaPagoResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaPago(inValue);
            return retVal.Body.GrabaPagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaPagoResponse> Web.wsAmazonSige.ServiceSoap.GrabaPagoAsync(Web.wsAmazonSige.GrabaPagoRequest request) {
            return base.Channel.GrabaPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaPagoResponse> GrabaPagoAsync(Web.wsAmazonSige.Npago pago, Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.GrabaPagoRequest inValue = new Web.wsAmazonSige.GrabaPagoRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaPagoRequestBody();
            inValue.Body.pago = pago;
            inValue.Body.usuario = usuario;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.GrabaPagoChequeResponse Web.wsAmazonSige.ServiceSoap.GrabaPagoCheque(Web.wsAmazonSige.GrabaPagoChequeRequest request) {
            return base.Channel.GrabaPagoCheque(request);
        }
        
        public string GrabaPagoCheque(Web.wsAmazonSige.Npago pago, Web.wsAmazonSige.NUsuario usuario, string tipoVenta) {
            Web.wsAmazonSige.GrabaPagoChequeRequest inValue = new Web.wsAmazonSige.GrabaPagoChequeRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaPagoChequeRequestBody();
            inValue.Body.pago = pago;
            inValue.Body.usuario = usuario;
            inValue.Body.tipoVenta = tipoVenta;
            Web.wsAmazonSige.GrabaPagoChequeResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaPagoCheque(inValue);
            return retVal.Body.GrabaPagoChequeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaPagoChequeResponse> Web.wsAmazonSige.ServiceSoap.GrabaPagoChequeAsync(Web.wsAmazonSige.GrabaPagoChequeRequest request) {
            return base.Channel.GrabaPagoChequeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaPagoChequeResponse> GrabaPagoChequeAsync(Web.wsAmazonSige.Npago pago, Web.wsAmazonSige.NUsuario usuario, string tipoVenta) {
            Web.wsAmazonSige.GrabaPagoChequeRequest inValue = new Web.wsAmazonSige.GrabaPagoChequeRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaPagoChequeRequestBody();
            inValue.Body.pago = pago;
            inValue.Body.usuario = usuario;
            inValue.Body.tipoVenta = tipoVenta;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaPagoChequeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.GrabaClienteResponse Web.wsAmazonSige.ServiceSoap.GrabaCliente(Web.wsAmazonSige.GrabaClienteRequest request) {
            return base.Channel.GrabaCliente(request);
        }
        
        public string GrabaCliente(Web.wsAmazonSige.NCliente cliente, Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.GrabaClienteRequest inValue = new Web.wsAmazonSige.GrabaClienteRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaClienteRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.usuario = usuario;
            Web.wsAmazonSige.GrabaClienteResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaCliente(inValue);
            return retVal.Body.GrabaClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaClienteResponse> Web.wsAmazonSige.ServiceSoap.GrabaClienteAsync(Web.wsAmazonSige.GrabaClienteRequest request) {
            return base.Channel.GrabaClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.GrabaClienteResponse> GrabaClienteAsync(Web.wsAmazonSige.NCliente cliente, Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.GrabaClienteRequest inValue = new Web.wsAmazonSige.GrabaClienteRequest();
            inValue.Body = new Web.wsAmazonSige.GrabaClienteRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.usuario = usuario;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).GrabaClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.ActualizaCorrelativoBoletaResponse Web.wsAmazonSige.ServiceSoap.ActualizaCorrelativoBoleta(Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest request) {
            return base.Channel.ActualizaCorrelativoBoleta(request);
        }
        
        public void ActualizaCorrelativoBoleta(Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest inValue = new Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest();
            inValue.Body = new Web.wsAmazonSige.ActualizaCorrelativoBoletaRequestBody();
            inValue.Body.usuario = usuario;
            Web.wsAmazonSige.ActualizaCorrelativoBoletaResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).ActualizaCorrelativoBoleta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.ActualizaCorrelativoBoletaResponse> Web.wsAmazonSige.ServiceSoap.ActualizaCorrelativoBoletaAsync(Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest request) {
            return base.Channel.ActualizaCorrelativoBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.ActualizaCorrelativoBoletaResponse> ActualizaCorrelativoBoletaAsync(Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest inValue = new Web.wsAmazonSige.ActualizaCorrelativoBoletaRequest();
            inValue.Body = new Web.wsAmazonSige.ActualizaCorrelativoBoletaRequestBody();
            inValue.Body.usuario = usuario;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).ActualizaCorrelativoBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.EliminarVentaSinBoletaResponse Web.wsAmazonSige.ServiceSoap.EliminarVentaSinBoleta(Web.wsAmazonSige.EliminarVentaSinBoletaRequest request) {
            return base.Channel.EliminarVentaSinBoleta(request);
        }
        
        public void EliminarVentaSinBoleta(Web.wsAmazonSige.NUsuario usuario, int correlativo) {
            Web.wsAmazonSige.EliminarVentaSinBoletaRequest inValue = new Web.wsAmazonSige.EliminarVentaSinBoletaRequest();
            inValue.Body = new Web.wsAmazonSige.EliminarVentaSinBoletaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.correlativo = correlativo;
            Web.wsAmazonSige.EliminarVentaSinBoletaResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).EliminarVentaSinBoleta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.EliminarVentaSinBoletaResponse> Web.wsAmazonSige.ServiceSoap.EliminarVentaSinBoletaAsync(Web.wsAmazonSige.EliminarVentaSinBoletaRequest request) {
            return base.Channel.EliminarVentaSinBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.EliminarVentaSinBoletaResponse> EliminarVentaSinBoletaAsync(Web.wsAmazonSige.NUsuario usuario, int correlativo) {
            Web.wsAmazonSige.EliminarVentaSinBoletaRequest inValue = new Web.wsAmazonSige.EliminarVentaSinBoletaRequest();
            inValue.Body = new Web.wsAmazonSige.EliminarVentaSinBoletaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.correlativo = correlativo;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).EliminarVentaSinBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.wsAmazonSige.InicioSesionResponse Web.wsAmazonSige.ServiceSoap.InicioSesion(Web.wsAmazonSige.InicioSesionRequest request) {
            return base.Channel.InicioSesion(request);
        }
        
        public bool InicioSesion(Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.InicioSesionRequest inValue = new Web.wsAmazonSige.InicioSesionRequest();
            inValue.Body = new Web.wsAmazonSige.InicioSesionRequestBody();
            inValue.Body.usuario = usuario;
            Web.wsAmazonSige.InicioSesionResponse retVal = ((Web.wsAmazonSige.ServiceSoap)(this)).InicioSesion(inValue);
            return retVal.Body.InicioSesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.wsAmazonSige.InicioSesionResponse> Web.wsAmazonSige.ServiceSoap.InicioSesionAsync(Web.wsAmazonSige.InicioSesionRequest request) {
            return base.Channel.InicioSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.wsAmazonSige.InicioSesionResponse> InicioSesionAsync(Web.wsAmazonSige.NUsuario usuario) {
            Web.wsAmazonSige.InicioSesionRequest inValue = new Web.wsAmazonSige.InicioSesionRequest();
            inValue.Body = new Web.wsAmazonSige.InicioSesionRequestBody();
            inValue.Body.usuario = usuario;
            return ((Web.wsAmazonSige.ServiceSoap)(this)).InicioSesionAsync(inValue);
        }
    }
}
